[package]
name = "kdlfmt-core"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "Library crate for kdlfmt: formatter, config, and parser helpers."
documentation = { workspace = true }
readme = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[features]
default = []
clap = ["dep:clap"]

[dependencies]
clap = { workspace = true, optional = true }
dashmap = { workspace = true }
ec4rs = { workspace = true }
kdl = { version = "6.5.0", git = "https://github.com/njreid/kdl-rs", rev = "05521dce0f3d2915f3fa6707f240c938dde3b818", features = ["v1", "expression-strings"] }
miette = { workspace = true }
thiserror = { workspace = true }
